(function(){
function g(a,c,b,e,d,f,h,j,i,l,m,k,p,q,r,n,o,s,t){this.c=a;this.R=c;this.b=b;this.a=e;this.D=i;this.q=l;this.I=d;this.K=f;this.J=h;this.L=j;this.T=m;this.S=k;this.Q=p;this.j=q;this.P=r;this.O=n;this.N=o;this.V=s||n;this.U=t||o;this.e=[];this.d=0;this.i=false;this.W=this.c.offsetHeight;this.k="";this.g="";this.p="";this.m=""}g.prototype.init=function(){var a=[],c=0;for(var b=this.c.firstChild;b;b=b.nextSibling)if(b.nodeType==1&&b.tagName=="LI"){var e=document.getElementById("taw"+c),d=this.h("a","adt",
e)[0],f=this.h("span",null,e)[0],h=this.h("div","adb",e)[0],j=this.h("span","adus",e)[0],i=this.w(c++,d.href,f.innerHTML,h.innerHTML,j.innerHTML);a.push(i)}this.e.push(a);this.H();this.R.style.display="block"};g.prototype.C=function(a){var c=0;for(var b=0;b<this.e.length;b++)c+=this.e[b].length;this.j=a.token&&a.token.length>0?a.token:null;var e=[];for(var b=0;b<a.ads.length;b++){var d=a.ads[b];d.id=c+b;e[b]=d}this.e.push(e);this.d++;this.l(e);this.o();this.i=false};g.prototype.v=function(a,c,b,e){var d=
document.createElement("li"),f="ss('','aw"+a.id+"')";d.id="taw"+a.id;d.setAttribute("onfocus",f);d.setAttribute("onmouseover",f);if(this.Q)d.setAttribute("dir","rtl");d.style.height=c?c+"px":"";d.style.width=b?b+"px":"";var h=document.createElement("div");h.className="ad";d.appendChild(h);var j;if(this.q==1){var i,l,m,k;i=document.createElement("table");i.setAttribute("cellpadding",0);i.setAttribute("cellspacing",0);i.setAttribute("border",0);i.className="adc";i.style.height=c?c+"px":"";i.style.width=
b?b+"px":"";h.appendChild(i);l=document.createElement("tbody");m=document.createElement("tr");k=document.createElement("td");k.setAttribute("valign","middle");m.appendChild(k);l.appendChild(m);i.appendChild(l);j=k}else j=h;var p=e?this.V:this.O,q=e?this.U:this.N,r="font-size: "+p+"px",n="font-size: "+q+"px",o="<a class=adt href="+a.url+" id=aw"+a.id+" onclick=\"ha('aw"+a.id+'\')" onfocus="'+f+'" onmousedown="st(\'aw'+a.id+'\')" onmouseover="return '+f+'" target=_top><span style="'+r+'">'+a.title+
'</span></a><div class=adb style="'+n+'">'+a.text+"</div><div class=adu><span class=adus id=uaw"+a.id+" onclick=ga(this,event) onmousedown=st(this.id.substr(1))>"+a.visibleUrl+"</span></div>";j.innerHTML=o;return d};g.prototype.w=function(a,c,b,e,d){var f={};f.id=a;f.url=c;f.title=b;f.text=e;f.visibleUrl=d;return f};g.prototype.z=function(){this.c.innerHTML='<li style="width:100%" id='+this.S+"><table><tbody><tr><td>"+this.T+"</td></tr></tbody></table>"};g.prototype.h=function(a,c,b){var e=b.getElementsByTagName(a),
d=[];for(var f=0,h;h=e[f];f++){var j=h.className;if(j.split(" ").indexOf(c)>=0)d.push(h)}return d.length?d:e};g.prototype.r=function(a){if(a==0&&this.d>0)this.u(this.B);else if(a==1&&(this.j||this.d<this.e.length-1))this.u(this.A)};g.prototype.s=function(a){this.n(a)};g.prototype.t=function(a){if(a==0&&this.d>0||a==1&&(this.j||this.d<this.e.length-1))this.G(a)};g.prototype.l=function(a){var c=0;for(var b=0;b<this.d;b++)c+=this.e[b].length;var e,d;if(this.q==0)d=Math.floor(this.c.offsetWidth/a.length);
else if(this.q==1&&this.P)e=Math.round(this.M/a.length);while(this.c.firstChild)this.c.removeChild(this.c.firstChild);for(var b=0;b<a.length;b++){var f=this.v(a[b],e,d,this.D==a.length);this.c.appendChild(f)}};g.prototype.A=function(){if(this.d==this.e.length-1){this.z();this.F(window.location.search)}else{var a=this.e[++this.d];this.l(a);this.o();this.i=false}};g.prototype.B=function(){var a=this.e[--this.d];this.l(a);this.o();this.i=false};g.prototype.u=function(a){if(!this.i){this.i=true;this.M=
this.c.parentNode.offsetHeight;while(this.c.firstChild)this.c.removeChild(this.c.firstChild);a.call(this)}};g.prototype.F=function(a){if(this.k==""||this.g==""||this.p==""||this.m==""){if(a.charAt(0)=="?")a=a.substring(1);var c=a.split("&");for(var b=0;b<c.length;b++){var e=c[b].split("=");if(e.length==2)switch(e[0]){case "client":this.k=e[1];break;case "format":this.g=e[1];break;case "url":this.p=e[1];break;case "prev_fmts":this.m=e[1];break}}}var d="/pagead/ads?output=smajs&targeting=content&ad_type=text&num_ads="+
this.D+"&tok="+this.j;if(this.k)d+="&client="+this.k;if(this.p)d+="&url="+this.p;if(this.g){d+="&format=sma-"+this.g;d+="&prev_fmts=";if(this.m)d+=this.m+"%2C";d+=this.g}var f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",d);var h=document.getElementsByTagName("head")[0];h.appendChild(f)};g.prototype.G=function(a){var c=a==0?this.b:this.a;c.style.backgroundColor=c.activeBgColor;c.style.cursor=c.activeCursor};g.prototype.n=function(a){var c=a==0?this.b:
this.a;c.style.backgroundColor=c.inactiveBgColor;c.style.cursor=c.inactiveCursor};g.prototype.o=function(){if(this.d>0)this.b.onmouseover=this.b.activeMouseOver;else{this.b.onmouseover=null;this.n(0)}if(this.j||this.d<this.e.length-1)this.a.onmouseover=this.a.activeMouseOver;else{this.a.onmouseover=null;this.n(1)}};g.prototype.H=function(){this.b.activeBgColor=this.I;this.b.inactiveBgColor=this.K;this.b.f=this;this.b.activeCursor=this.J;this.b.inactiveCursor=this.L;this.b.onmousedown=function(){this.f.r(0)};
this.b.activeMouseOver=function(){this.f.t(0)};this.b.onmouseout=function(){this.f.s(0)};this.b.onmouseover=this.b.activeMouseOver;this.b.onmouseout();this.a.activeBgColor=this.I;this.a.inactiveBgColor=this.K;this.a.f=this;this.a.activeCursor=this.J;this.a.inactiveCursor=this.L;this.a.onmousedown=function(){this.f.r(1)};this.a.activeMouseOver=function(){this.f.t(1)};this.a.onmouseout=function(){this.f.s(1)};this.a.onmouseover=this.a.activeMouseOver;this.a.onmouseout()};if(!Array.prototype.indexOf)Array.prototype.indexOf=
function(a){for(var c=0;c<this.length;c++)if(this[c]==a)return c;return-1};if(window.sma){window.smaSlotManager=new g(document.getElementById(sma[0]),document.getElementById(sma[1]),document.getElementById(sma[2]),document.getElementById(sma[3]),sma[4],sma[5],sma[6],sma[7],sma[8],sma[9],sma[10],sma[11],sma[12],sma[13],sma[14],sma[15],sma[16],sma[17],sma[18]);window.smaSlotManager.init();window.handleAdsRequestDone=function(a){window.smaSlotManager.C(a)}};
})()
